### ISSUE TITLE
10.0.2 release note being edited

### ISSUE THREAD

**Issue by agiguere** [SAP/cloud-sdk-ios#94]
We would like to know why a version 10.0.2 after releasing 24.4.0?

there is no clear blog or explanation about why you still releasing version 9.x and 10.x

also the release of 10.0.2 is still being edited, we can't check what has been change

thanks

**Comment by serajahmad01** [comment]
Hi Alexandre,

Please check [this blog] (https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-sdk-for-ios-24-4-0-is-now-available/ba-p/13663931) for the change in the SDK versioning format.

We are releasing the 9.x and 10.x patches despite the new major version 24.4 because some customers may not be ready to transition to a new major version just yet. This way, customers can still benefit from the minor improvements included in patch releases.

The release note for 10.0.2 is available now. We will ensure to update the notes along with our releases from now on.

Thanks,
Seraj

**Comment by agiguere** [comment]
thanks
